### ISSUE TITLE
Mullvad 2020.1 beta does not install

### ISSUE THREAD

**Issue by rdebruin** [mullvad/mullvadvpn-app#1467]
Mullvad 2020 beta 1 does not install Attached a logfile.

![Aantekening 2020-02-09 131834](https://user-images.githubusercontent.com/31158197/74101953-37d5c200-4b3f-11ea-8884-030e149251b2.jpg)
[install.log](https://github.com/mullvad/mullvadvpn-app/files/4176850/install.log)

**Comment by rdebruin** [comment]
I noticed the same behaviour with IVPN (another VPN client), but there the client reboots my PC and I can install the client afterwards.

**Comment by rdebruin** [comment]
By accident closed it.

**Comment by faern** [comment]
So this was resolved after rebooting your computer? You were able to install the beta eventually?

**Comment by rdebruin** [comment]
Hi Linus,

Yes, after a reboot I could install the beta. However, I had to reboot it
manually and with (e.g.) the IVPN client the system rebooted automatically
during install of their client.

Op ma 10 feb. 2020 om 11:17 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by rdebruin** [comment]
Please note that a reboot before the install does not solve the problem (tried it 3 times). I have to reboot after the failed first install. I had to search through the install.log file to find a reason. Is it possible to reboot the PC when the install issues a return code? I noticed the error code in the install.log file.

**Comment by rdebruin** [comment]
SupportAssistent (Dell utility/service) that was running is the background caused the issue. Reinstalled it and the problem solved.
