### ISSUE TITLE
Compiling ios on mac keeps getting errors: Command ExternalBuildToolExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by linnyzhang** [mullvad/mullvadvpn-app#2257]
Compiling ios on mac keeps getting errors: Command ExternalBuildToolExecution failed with a nonzero exit code
Module: wireguard go bridge

Compiler Environment:
Mac os :10.15.7
Go version:go version go1.15.2 darwin/amd64
Xcode:12.0.1

**Comment by faern** [comment]
Our iOS dev is currently not available. But I'm sure they will reply later.

**Comment by pronebird** [comment]
@linnyzhang could you post the whole build log please?

**Comment by linnyzhang** [comment]
@faern @pronebird Thank you for quickly responding to my question.
Xcode log:
ExternalBuildToolExecution WireGuardGoBridge (in target 'WireGuardGoBridge' from project 'MullvadVPN')
    cd /Users/clark/Documents/github/mullvadvpn-app/ios/wireguard-go-bridge
    export ACTION\=
    export AD_HOC_CODE_SIGNING_ALLOWED\=YES
    export ALTERNATE_GROUP\=staff
    export ALTERNATE_MODE\=u+w,go-w,a+rX
    export ALTERNATE_OWNER\=clark
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
    export ALWAYS_SEARCH_USER_PATHS\=NO
    export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR\=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY\=NO
    export APPLY_RULES_IN_COPY_FILES\=NO
    export APPLY_RULES_IN_COPY_HEADERS\=NO
    export ARCHS\=x86_64
    export ARCHS_STANDARD\=arm64\ x86_64
    export ARCHS_STANDARD_32_64_BIT\=arm64\ i386\ x86_64
    export ARCHS_STANDARD_32_BIT\=i386
    export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64
    export ARCHS_UNIVERSAL_IPHONE_OS\=arm64\ i386\ x86_64
    export ASSETCATALOG_FILTER_FOR_DEVICE_MODEL\=iPod9,1
    export ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION\=14.1
    export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
    export BITCODE_GENERATION_MODE\=clarker
    export BUILD_ACTIVE_RESOURCES_ONLY\=YES
    export BUILD_COMPONENTS\=headers\ build
    export BUILD_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products
    export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
    export BUILD_ROOT\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products
    export BUILD_STYLE\=
    export BUILD_VARIANTS\=normal
    export BUILT_PRODUCTS_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator
    export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
    export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
    export BUNDLE_FORMAT\=shallow
    export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Frameworks
    export BUNDLE_PLUGINS_FOLDER_PATH\=PlugIns
    export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=PrivateHeaders
    export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Headers
    export CACHE_ROOT\=/var/folders/pk/s66p676j4bb5646_bs8dn6wc0000gp/C/com.apple.DeveloperTools/12.1-12A7403/Xcode
    export CLANG_ANALYZER_NONNULL\=YES
    export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION\=YES_AGGRESSIVE
    export CLANG_CXX_LANGUAGE_STANDARD\=gnu++14
    export CLANG_CXX_LIBRARY\=libc++
    export CLANG_ENABLE_MODULES\=YES
    export CLANG_ENABLE_OBJC_ARC\=YES
    export CLANG_ENABLE_OBJC_WEAK\=YES
    export CLANG_MODULES_BUILD_SESSION_FILE\=/Users/clark/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
    export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING\=YES
    export CLANG_WARN_BOOL_CONVERSION\=YES
    export CLANG_WARN_COMMA\=YES
    export CLANG_WARN_CONSTANT_CONVERSION\=YES
    export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS\=YES
    export CLANG_WARN_DIRECT_OBJC_ISA_USAGE\=YES_ERROR
    export CLANG_WARN_DOCUMENTATION_COMMENTS\=YES
    export CLANG_WARN_EMPTY_BODY\=YES
    export CLANG_WARN_ENUM_CONVERSION\=YES
    export CLANG_WARN_INFINITE_RECURSION\=YES
    export CLANG_WARN_INT_CONVERSION\=YES
    export CLANG_WARN_NON_LITERAL_NULL_CONVERSION\=YES
    export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF\=YES
    export CLANG_WARN_OBJC_LITERAL_CONVERSION\=YES
    export CLANG_WARN_OBJC_ROOT_CLASS\=YES_ERROR
    export CLANG_WARN_RANGE_LOOP_ANALYSIS\=YES
    export CLANG_WARN_STRICT_PROTOTYPES\=YES
    export CLANG_WARN_SUSPICIOUS_MOVE\=YES
    export CLANG_WARN_UNGUARDED_AVAILABILITY\=YES_AGGRESSIVE
    export CLANG_WARN_UNREACHABLE_CODE\=YES
    export CLANG_WARN__DUPLICATE_METHOD_MATCH\=YES
    export CLASS_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/JavaClasses
    export CLONE_HEADERS\=NO
    export CODE_SIGNING_ALLOWED\=NO
    export CODE_SIGN_CONTEXT_CLASS\=XCiPhoneSimulatorCodeSignContext
    export CODE_SIGN_IDENTITY\=Apple\ Development
    export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
    export CODE_SIGN_STYLE\=Automatic
    export COLOR_DIAGNOSTICS\=NO
    export COMPILER_INDEX_STORE_ENABLE\=Default
    export COMPRESS_PNG_FILES\=YES
    export CONFIGURATION\=Debug
    export CONFIGURATION_BUILD_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator
    export CONFIGURATION_TEMP_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator
    export COPYING_PRESERVES_HFS_DATA\=NO
    export COPY_HEADERS_RUN_UNIFDEF\=NO
    export COPY_PHASE_STRIP\=NO
    export CORRESPONDING_DEVICE_PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
    export CORRESPONDING_DEVICE_PLATFORM_NAME\=iphoneos
    export CORRESPONDING_DEVICE_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.1.sdk
    export CORRESPONDING_DEVICE_SDK_NAME\=iphoneos14.1
    export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
    export DEAD_CODE_STRIPPING\=YES
    export DEBUGGING_SYMBOLS\=YES
    export DEBUG_INFORMATION_FORMAT\=dwarf
    export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export DEFINES_MODULE\=NO
    export DEPLOYMENT_LOCATION\=NO
    export DEPLOYMENT_POSTPROCESSING\=NO
    export DEPLOYMENT_TARGET_CLANG_ENV_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_CLANG_FLAG_NAME\=mios-simulator-version-min
    export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX\=-mios-simulator-version-min\=
    export DEPLOYMENT_TARGET_LD_ENV_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_LD_FLAG_NAME\=ios_simulator_version_min
    export DEPLOYMENT_TARGET_SETTING_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DERIVED_FILES_DIR\=
    export DERIVED_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/DerivedSources
    export DERIVED_SOURCES_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE\=en
    export DONT_GENERATE_INFOPLIST_FILE\=NO
    export DO_HEADER_SCANNING_IN_JAM\=NO
    export DSTROOT\=/tmp/MullvadVPN.dst
    export DT_TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME\=.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
    export DWARF_DSYM_FOLDER_PATH\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator
    export EFFECTIVE_PLATFORM_NAME\=-iphonesimulator
    export EMBEDDED_CONTENT_CONTAINS_SWIFT\=NO
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE\=NO
    export ENABLE_BITCODE\=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS\=YES
    export ENABLE_HARDENED_RUNTIME\=NO
    export ENABLE_HEADER_DEPENDENCIES\=YES
    export ENABLE_ON_DEMAND_RESOURCES\=NO
    export ENABLE_PREVIEWS\=NO
    export ENABLE_STRICT_OBJC_MSGSEND\=YES
    export ENABLE_TESTABILITY\=YES
    export ENABLE_TESTING_SEARCH_PATHS\=NO
    export ENTITLEMENTS_DESTINATION\=__entitlements
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS\=.DS_Store\ .svn\ .git\ .hg\ CVS
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES\=\*.nib\ \*.lproj\ \*.framework\ \*.gch\ \*.xcode\*\ \*.xcassets\ \(\*\)\ .DS_Store\ CVS\ .svn\ .git\ .hg\ \*.pbproj\ \*.pbxproj
    export FILE_LIST\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/Objects/LinkFileList
    export FRAMEWORK_VERSION\=A
    export GCC3_VERSION\=3.3
    export GCC_C_LANGUAGE_STANDARD\=gnu11
    export GCC_DYNAMIC_NO_PIC\=NO
    export GCC_GENERATE_DEBUGGING_SYMBOLS\=YES
    export GCC_NO_COMMON_BLOCKS\=YES
    export GCC_OBJC_LEGACY_DISPATCH\=YES
    export GCC_OPTIMIZATION_LEVEL\=0
    export GCC_PREPROCESSOR_DEFINITIONS\=DEBUG\=1\
    export GCC_VERSION\=com.apple.compilers.llvm.clang.1_0
    export GCC_WARN_64_TO_32_BIT_CONVERSION\=YES
    export GCC_WARN_ABOUT_RETURN_TYPE\=YES_ERROR
    export GCC_WARN_UNDECLARED_SELECTOR\=YES
    export GCC_WARN_UNINITIALIZED_AUTOS\=YES_AGGRESSIVE
    export GCC_WARN_UNUSED_FUNCTION\=YES
    export GCC_WARN_UNUSED_VARIABLE\=YES
    export GENERATED_MODULEMAP_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/GeneratedModuleMaps-iphonesimulator
    export GENERATE_MASTER_OBJECT_FILE\=NO
    export GENERATE_PKGINFO_FILE\=NO
    export GENERATE_PROFILING_CODE\=NO
    export GENERATE_TEXT_BASED_STUBS\=NO
    export GID\=20
    export GROUP\=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT\=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES\=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS\=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS\=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES\=YES
    export HEADERMAP_USES_VFS\=NO
    export HIDE_BITCODE_SYMBOLS\=YES
    export HOME\=/Users/clark
    export INFOPLIST_EXPAND_BUILD_SETTINGS\=YES
    export INFOPLIST_OUTPUT_FORMAT\=binary
    export INFOPLIST_PREPROCESS\=NO
    export INLINE_PRIVATE_FRAMEWORKS\=NO
    export INSTALLHDRS_COPY_PHASE\=NO
    export INSTALLHDRS_SCRIPT_PHASE\=NO
    export INSTALL_DIR\=/tmp/MullvadVPN.dst
    export INSTALL_GROUP\=staff
    export INSTALL_MODE_FLAG\=u+w,go-w,a+rX
    export INSTALL_OWNER\=clark
    export INSTALL_ROOT\=/tmp/MullvadVPN.dst
    export IPHONEOS_DEPLOYMENT_TARGET\=12.0
    export JAVA_APP_STUB\=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES\=YES
    export JAVA_ARCHIVE_TYPE\=JAR
    export JAVA_COMPILER\=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS\=Resources
    export JAVA_JAR_FLAGS\=cv
    export JAVA_SOURCE_SUBDIR\=.
    export JAVA_USE_DEPENDENCIES\=YES
    export JAVA_ZIP_FLAGS\=-urg
    export KEEP_PRIVATE_EXTERNS\=NO
    export LD_DEPENDENCY_INFO_FILE\=//WireGuardGoBridge_dependency_info.dat
    export LD_GENERATE_MAP_FILE\=NO
    export LD_MAP_FILE_PATH\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/WireGuardGoBridge-LinkMap--.txt
    export LD_NO_PIE\=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER\=YES
    export LEGACY_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LIBRARY_DEXT_INSTALL_PATH\=/Library/DriverExtensions
    export LIBRARY_FLAG_NOSPACE\=YES
    export LIBRARY_KEXT_INSTALL_PATH\=/Library/Extensions
    export LINKER_DISPLAYS_MANGLED_NAMES\=NO
    export LINK_FILE_LIST_normal_x86_64\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/Objects-normal/x86_64/WireGuardGoBridge.LinkFileList
    export LINK_WITH_STANDARD_LIBRARIES\=YES
    export LLVM_TARGET_TRIPLE_OS_VERSION\=ios12.0
    export LLVM_TARGET_TRIPLE_SUFFIX\=-simulator
    export LLVM_TARGET_TRIPLE_VENDOR\=apple
    export LOCALIZED_STRING_MACRO_NAMES\=NSLocalizedString\ CFCopyLocalizedString
    export LOCALIZED_STRING_SWIFTUI_SUPPORT\=YES
    export LOCAL_ADMIN_APPS_DIR\=/Applications/Utilities
    export LOCAL_APPS_DIR\=/Applications
    export LOCAL_DEVELOPER_DIR\=/Library/Developer
    export LOCAL_LIBRARY_DIR\=/Library
    export LOCROOT\=/Users/clark/Documents/github/mullvadvpn-app/ios
    export LOCSYMROOT\=/Users/clark/Documents/github/mullvadvpn-app/ios
    export MAC_OS_X_PRODUCT_BUILD_VERSION\=19H2
    export MAC_OS_X_VERSION_ACTUAL\=101507
    export MAC_OS_X_VERSION_MAJOR\=101500
    export MAC_OS_X_VERSION_MINOR\=1507
    export METAL_LIBRARY_FILE_BASE\=default
    export METAL_LIBRARY_OUTPUT_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator/
    export MODULE_CACHE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
    export MTL_ENABLE_DEBUG_INFO\=INCLUDE_SOURCE
    export MTL_FAST_MATH\=YES
    export NATIVE_ARCH\=x86_64
    export NATIVE_ARCH_32_BIT\=i386
    export NATIVE_ARCH_64_BIT\=x86_64
    export NATIVE_ARCH_ACTUAL\=x86_64
    export OBJC_ABI_VERSION\=2
    export OBJECT_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/Objects
    export OBJROOT\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex
    export ONLY_ACTIVE_ARCH\=YES
    export OS\=MACOS
    export PATH\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES\=/usr/include\ /usr/local/include\ /System/Library/Frameworks\ /System/Library/PrivateFrameworks\ /Applications/Xcode.app/Contents/Developer/Headers\ /Applications/Xcode.app/Contents/Developer/SDKs\ /Applications/Xcode.app/Contents/Developer/Platforms
    export PER_ARCH_OBJECT_FILE_DIR\=/
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
    export PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
    export PLATFORM_DISPLAY_NAME\=iOS\ Simulator
    export PLATFORM_FAMILY_NAME\=iOS
    export PLATFORM_NAME\=iphonesimulator
    export PLATFORM_PREFERRED_ARCH\=x86_64
    export PLATFORM_PRODUCT_BUILD_VERSION\=18A8394
    export PLIST_FILE_OUTPUT_FORMAT\=binary
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
    export PRECOMP_DESTINATION_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
    export PRODUCT_MODULE_NAME\=WireGuardGoBridge
    export PRODUCT_NAME\=WireGuardGoBridge
    export PROFILING_CODE\=NO
    export PROJECT\=MullvadVPN
    export PROJECT_DERIVED_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/DerivedSources
    export PROJECT_DIR\=/Users/clark/Documents/github/mullvadvpn-app/ios
    export PROJECT_FILE_PATH\=/Users/clark/Documents/github/mullvadvpn-app/ios/MullvadVPN.xcodeproj
    export PROJECT_NAME\=MullvadVPN
    export PROJECT_TEMP_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build
    export PROJECT_TEMP_ROOT\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex
    export REMOVE_CVS_FROM_RESOURCES\=YES
    export REMOVE_GIT_FROM_RESOURCES\=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
    export REMOVE_HG_FROM_RESOURCES\=YES
    export REMOVE_SVN_FROM_RESOURCES\=YES
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk
    export SEPARATE_STRIP\=NO
    export SEPARATE_SYMBOL_EDIT\=NO
    export SHARED_DERIVED_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator/DerivedSources
    export SHARED_PRECOMPS_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/PrecompiledHeaders
    export SKIP_INSTALL\=YES
    export SOURCE_ROOT\=/Users/clark/Documents/github/mullvadvpn-app/ios
    export SRCROOT\=/Users/clark/Documents/github/mullvadvpn-app/ios
    export STRINGS_FILE_OUTPUT_ENCODING\=binary
    export STRIP_BITCODE_FROM_COPIED_FILES\=NO
    export STRIP_INSTALLED_PRODUCT\=YES
    export STRIP_STYLE\=all
    export STRIP_SWIFT_SYMBOLS\=YES
    export SUPPORTED_PLATFORMS\=iphoneos\ iphonesimulator
    export SUPPORTS_TEXT_BASED_API\=NO
    export SWIFT_ACTIVE_COMPILATION_CONDITIONS\=DEBUG
    export SWIFT_OPTIMIZATION_LEVEL\=-Onone
    export SWIFT_PLATFORM_TARGET_PREFIX\=ios
    export SWIFT_RESPONSE_FILE_PATH_normal_x86_64\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build/Objects-normal/x86_64/WireGuardGoBridge.SwiftFileList
    export SYMROOT\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products
    export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
    export SYSTEM_APPS_DIR\=/Applications
    export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR\=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
    export SYSTEM_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Java\ Tools
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Performance\ Tools
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
    export SYSTEM_DEVELOPER_TOOLS\=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes/DeveloperTools
    export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR\=/System/Library
    export TAPI_VERIFY_MODE\=ErrorsOnly
    export TARGETED_DEVICE_FAMILY\=1
    export TARGETNAME\=WireGuardGoBridge
    export TARGET_BUILD_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Products/Debug-iphonesimulator
    export TARGET_DEVICE_IDENTIFIER\=51EC910C-0955-497E-BD31-493BDE12F744
    export TARGET_DEVICE_MODEL\=iPod9,1
    export TARGET_DEVICE_OS_VERSION\=14.1
    export TARGET_NAME\=WireGuardGoBridge
    export TARGET_TEMP_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build
    export TEMP_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build
    export TEMP_FILES_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build
    export TEMP_FILE_DIR\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/WireGuardGoBridge.build
    export TEMP_ROOT\=/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex
    export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
    export UID\=502
    export USER\=clark
    export USER_APPS_DIR\=/Users/clark/Applications
    export USER_LIBRARY_DIR\=/Users/clark/Library
    export USE_HEADERMAP\=YES
    export USE_LLVM_TARGET_TRIPLES\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
    export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
    export VALIDATE_WORKSPACE\=YES_ERROR
    export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
    export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION\=12A7403
    export XCODE_VERSION_ACTUAL\=1210
    export XCODE_VERSION_MAJOR\=1200
    export XCODE_VERSION_MINOR\=1210
    export arch\=undefined_arch
    export variant\=normal
    /usr/bin/make

[ -n "" ]
make: *** [/Users/clark/Library/Developer/Xcode/DerivedData/MullvadVPN-frnekenvczjzakfshzkhlygoscbn/Build/Intermediates.noindex/MullvadVPN.build/Debug-iphonesimulator/wireguard-go-bridge/goroot/.prepared] Error 1
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by pronebird** [comment]
@linnyzhang try installing Go 1.13.4 instead of Go 1.15. I think that should fix the issue. You can also run a test build of `wireguard-go-bridge` by typing the following commands in your terminal:

```
cd <path-to-mullvadvpn-app-repo>/ios/wireguard-go-bridge
make
```

**Comment by linnyzhang** [comment]
@pronebird Installing Go version 1.13.4, but still the same error:

clark@MacBook-Pro ios % go version
go version go1.13.4 darwin/amd64


Compiling wireguard-go-bridge separately is no error, and libwg-go-arm64.a and libwg-go-armv7.a are generated

**Comment by pronebird** [comment]
@linnyzhang by looking at your original build log, it looks to me that something is not available to Xcodebuild.

As per your log file:

```
/usr/bin/make

[ -n "" ]
```

It seems to me that the `-n` argument is missing.

If I get it right, it looks like this part of `Makefile` is responsible for passing this flag:

```
REAL_GOROOT := $(shell go env GOROOT 2>/dev/null)
export GOROOT := $(BUILDDIR)/goroot
$(GOROOT)/.prepared:
	[ -n "$(REAL_GOROOT)" ]
```


That's said it looks like `go env GOROOT` is not available in the environment which runs `xcodebuild`. I am not sure what you use but I think Homebrew makes sure that all installed libraries are available on the machine. Maybe try installing go with Homebrew:

```
brew install go@1.13
```

My best guess is that you have Go installed and available to your active user but not to other users on the machine. This should explain why you see the failure to build `wireguard-go-bridge` from Xcode, but it works when you  build it manually. When I build it on my machine, the correct path appears in the output, i.e:

```
make      
[ -n "/usr/local/Cellar/go/1.13.1/libexec" ]
```

**Comment by linnyzhang** [comment]
@pronebird Thank you very much for your guidance. I deleted gvm and it worked after reinstalling go.
