### ISSUE TITLE
mullvad gui doesn't open in fedora 35 beta [workaround found]

### ISSUE THREAD

**Issue by pizzadude** [mullvad/mullvadvpn-app#2992]
## Issue report

Fedora 35 KDE Beta

mullvad-vpn-2021.4.0-1.x86_64

### Issue description

The mullvad gui doesn't launch in Fedora 35 KDE Beta. I upgraded from Fedora 34 KDE to Fedora 35 KDE Beta. The tray icon shows, but the gui itself doesn't launch.

If I launch mullvad-gui via the terminal, this is the output.

```
cd /opt/Mullvad VPN
./mullvad-gui                                                                                                                     
[2021-09-28 20:22:10.795][debug] Chromium sandbox is enabled
[2021-09-28 20:22:10.798][info] Running version 2021.4
Gtk-Message: 20:22:11.113: Failed to load module "appmenu-gtk-module"
Gtk-Message: 20:22:11.114: Failed to load module "appmenu-gtk-module"
[2021-09-28 20:22:11.349][info] Detected locale: en-GB
[2021-09-28 20:22:11.395][info] Connected to the daemon
[2021-09-28 20:22:12.571][error] Failed to load index file: ERR_FAILED (-2) loading 'file:///opt/Mullvad VPN/resources/app.asar/build/src/renderer/index.html'
```

Maybe it needs to be recompiled or something?

**Comment by pizzadude** [comment]
I figured it out.

/proc/sys/kernel/unprivileged_userns_clone does not exist in Fedora 35.

I edited /opt/Mullvad VPN/mullvad-vpn to run the gui with the --no-sandbox flag, now it works.

**Comment by KnugiHK** [comment]
Same problem occurs in Ubuntu 21.10 Impish with MullvadVPN-2021.4_amd64.
```
$ /opt/Mullvad\ VPN/mullvad-vpn 
[2021-10-02 13:52:28.043][debug] Chromium sandbox is enabled
[2021-10-02 13:52:28.045][info] Running version 2021.4
[2021-10-02 13:52:28.129][info] Detected locale: en-GB
[2021-10-02 13:52:28.137][info] Connected to the daemon
[2021-10-02 13:52:28.339][error] Failed to load index file: ERR_FAILED (-2) loading 'file:///opt/Mullvad VPN/resources/app.asar/build/src/renderer/index.html'
[11241:1002/135229.157307:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
Btw, @pizzadude's workaround works for me.

**Comment by pizzadude** [comment]
It might be an issue that is affecting a lot of electron apps recently.

**Comment by KnugiHK** [comment]
Seems that a simple upgrade of Electron is enough to fix it. I noticed the Electron version of 2021.4 is [11.2.3](https://github.com/mullvad/mullvadvpn-app/blob/c905a31ed0371c0feb982fbfd102dac940191a61/gui/package.json#L67) and the master branch is [15.0.0](https://github.com/mullvad/mullvadvpn-app/blob/0556f7e2960699bb8022247bcfe33d5c215c1955/gui/package.json#L63) currently. I built the app from master branch and the problem is gone.

**Comment by strykenKN** [comment]
is all well and good that it works for you now, but how about describing a simple way to overcome the problem ? Or do you just not care ? Not everyone is as tech savvy as you, so what is the easy way around the problem ? 

Please reply !

**Comment by strykenKN** [comment]
> I figured it out.
> 
> /proc/sys/kernel/unprivileged_userns_clone does not exist in Fedora 35.
> 
> I edited /opt/Mullvad VPN/mullvad-vpn to run the gui with the --no-sandbox flag, now it works.

aha and how is the way there, can you describe the auc h ? Not everyone is as technically savvy as you!

I hate it when you say you solved it, but for others you do not write the way there to solve it ?

So what is the single step under Fedora and how to do what ? Or don't you care at all ?

**Comment by pizzadude** [comment]
@strykenKN Be patient please.

Copy "/opt/Mullvad VPN/mullvad-vpn" to "/opt/Mullvad VPN/mullvad-vpn.bak"

Edit "/opt/Mullvad VPN/mullvad-vpn" and replace it with:

```
#!/usr/bin/env bash
set -eu

UNPRIVILEGED_USERNS_PATH="/proc/sys/kernel/unprivileged_userns_clone"
if [ -e $UNPRIVILEGED_USERNS_PATH ] && grep -q 0 $UNPRIVILEGED_USERNS_PATH; then
    SANDBOX_FLAG="--no-sandbox"
else
    SANDBOX_FLAG=""
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec "$SCRIPT_DIR/mullvad-gui" --no-sandbox "$@"
```

**Comment by raksooo** [comment]
Thanks for reporting this and providing a workaround! As mentioned earlier in this thread the issue is that the sandbox in the Electron version used in the current version of the app isn't compatible with newer versions of glibc. We're planning to release a new beta version soon which will disable the sandbox on Linux. And then in the next version after that we'll include Electron 15 and re-enable the sandbox. I'll leave this issue open until the beta is released.

**Comment by jacksongoode** [comment]
Doesn't seem that the new beta fixes this issue.

**Comment by raksooo** [comment]
For Ubuntu 21.10 this is now fixed. As mentioned in https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468, `glibc - 2.34-0ubuntu3` includes a fix for this and that version of glibc was included in the stable version of 21.10.

**Comment by riekusr** [comment]
experiencing the same in a fresh install of fedora 35. Waiting for a fix

**Comment by strykenKN** [comment]
the problem is unfortunately not fixed! Under Fedora 35 the GUI does not open and the app does not open in any way. 

Guys what is this ? It sucks and I really have no more nerve on it! 

Act finally!

**Comment by strykenKN** [comment]
> @jacksongoode This fix is not part of the current beta (2021.5-beta1) and will not be part of the final 2021.5 release. It's currently planned to be included in 2021.6 (and the 2021.6 betas).

Am I to understand that you are releasing a new app, but it will not fix the problems? You're not serious now, are you? Is this how you deal with paying customers? It's unbelievable how you deal with customers and the customers have to deal with problems, that's not possible!

You know for weeks, even months that new versions come out, you know about the problems and you change nothing, let the problems just exist. But the main thing is that the customer has paid, the main thing is that you have the money and we as paying customers are the stupid ones, simply because you do not fix the problems and we are dependent on the fact that you bring out a new beta at some point, in weeks, in months, but as long as the customer pays, the world is fine, right?  Unbelievable!

Translated with www.DeepL.com/Translator (free version)

**Comment by pizzadude** [comment]
@strykenKN Apply the workaround, or wait. Stop being rude.

**Comment by strykenKN** [comment]
> @strykenKN Apply the workaround, or wait. Stop being rude.

the workaround just does not work! The app starts but it remains white!

**Comment by pizzadude** [comment]
> > @strykenKN Apply the workaround, or wait. Stop being rude.
> 
> the workaround just does not work! The app starts but it remains white!

works 4 me

**Comment by pizzadude** [comment]
@strykenKN you either
1. haven't applied the workaround properly
2. recently updated your mullvad app, and need to apply the workaround again, as the mullvad update overwrote the file you're supposed to edit in the workaround

**Comment by strykenKN** [comment]
> @strykenKN you either
> 
>     1. haven't applied the workaround properly
> 
>     2. recently updated your mullvad app, and need to apply the workaround again, as the mullvad update overwrote the file you're supposed to edit in the workaround

hm... i tried again. Only now it worked, after hours and could not find the error. And then I tried everything again, step by step and now all of a sudden it works. Strange.

**Comment by faern** [comment]
We are working on producing a new beta which will solve this issue. In the meantime, please either use the workaround or wait a bit before upgrading your OS.

**Comment by faern** [comment]
@strykenKN This repository might not have any published community guidelines. But that does not mean it's OK to be rude. Please watch your language and tone. Let's try to have a constructive discussion around the issue.

**Comment by faern** [comment]
IMO, the main problem here is that Electron has an extremely short support window. Electron 11, which is what is broken here, was released less than a year ago and already can't start properly on modern distributions.

**Comment by faern** [comment]
We have now released [`2021.6-beta1`](https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.6-beta1) where this issue should be fixed! No workaround needed, the sandbox can be left on etc. Please try this beta out and see if it helps. I will close this issue as the beta comes closer to stable release.

**Comment by jacksongoode** [comment]
> We have now released [`2021.6-beta1`](https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.6-beta1) where this issue should be fixed! No workaround needed, the sandbox can be left on etc. Please try this beta out and see if it helps. I will close this issue as the beta comes closer to stable release.

It works! :partying_face:

**Comment by pizzadude** [comment]
Thanks, it works now.

**Comment by roundoutandabout** [comment]
> We have now released [`2021.6-beta1`](https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.6-beta1) where this issue should be fixed! No workaround needed, the sandbox can be left on etc. Please try this beta out and see if it helps. I will close this issue as the beta comes closer to stable release.

Works for me too. Thank you guys for the quick fix. You are great!

**Comment by ceit** [comment]
This fixes the same problem on openSUSE Tumbleweed (rolling release) with glibc 2.34.

**Comment by blutch112** [comment]
It's good it works on Ubuntu 21.10 and Fedora 35. Thanks

**Comment by raksooo** [comment]
Closing since the fix seems to be working well for everyone.
