### ISSUE TITLE
Reconnect loop on wake of Mac laptop

### ISSUE THREAD

**Issue by jmshurst** [mullvad/mullvadvpn-app#606]
**Issue:** When connected to VPN, close lid of laptop. When waking up, Mullvad client will go in a loop trying to reconnect, but won't ever connect. Internet traffic is blocked until the client is quit. In the client UI, the connecting screen flaps from connecting to disconnected, but the button to disconnect is non-responsive. Quitting or force quitting the app is the only way to resolve.

**Comment by faern** [comment]
Thanks for reporting this. We will look into it. What version of macOS and what version of the app are you running?

**Comment by viciuzvoid** [comment]
Similar on windows 10. App will not connect, just loops indefinitely and blocking network until exit.

**Comment by faern** [comment]
@viciuzvoid Please send a problem report from within the app to our support. The first macOS problem we can reproduce, but the thing you are describing I think is new.

**Comment by viciuzvoid** [comment]
> @viciuzvoid Please send a problem report from within the app to our support. The first macOS problem we can reproduce, but the thing you are describing I think is new.

I have now submitted a error report from within the app. Hope the logs helps :D

**Comment by faern** [comment]
@jmshurst Hi! We just released the 2018.6 version of the app. It does have some fixes with regards to offline detection on macOS. Could you try upgrading to that version and report whether or not that fixes the issues you were having?

**Comment by eero3** [comment]
I had the same problem as @viciuzvoid with 2018.6 version on Windows 10 laptop. It started happening suddenly after a reboot. Couldn't figure out the root cause, but reinstalling Mullvad seems to have fixed the problem.

**Comment by dtsepelev** [comment]
Same here. Using 2019.1 and the problem is 100% similar to the problem described by @jmshurst

**Comment by pronebird** [comment]
Hello, 

We've patched the issue with similar symptoms. I believe this should be finally fixed with the upcoming update.

**Comment by pronebird** [comment]
@faern was this fixed?

**Comment by faern** [comment]
I don't know. But since we have patched similar issues I think we can regard this as fixed until someone reports they are having this problem still.
