### ISSUE TITLE
Javascript error occured in main process ENOENT index.node not found

### ISSUE THREAD

**Issue by LiberteIV** [mullvad/mullvadvpn-app#7671]
### Is it a bug?

- [x] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [x] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

![Image](https://github.com/user-attachments/assets/f2e54c7a-5b70-447b-b73a-7eecb11df8b5)

### Expected Behavior

-

### Steps to Reproduce

1. ...
2. ...
3. affected only latest version (atleast for me)
system: windows 10 + mullvadvpn v2025.4

### Failure Logs

```shell

```

### Operating system version

windows 10

### Mullvad VPN app version

2025.4

**Comment by hulthe** [comment]
How often does this happen?
Does reinstalling help?
Do you have an anti-virus?

**Comment by presentformyfriends** [comment]
Experiencing similar (same?) error on Linux Mint 22.04 Xia XFCE when starting or quitting Mullvad VPN from the GUI:

![Image](https://github.com/user-attachments/assets/11d25145-f2c8-41a8-9eb5-f7c830288e65)

Here is what happens in my case. I tried to install with this command as per the docs:

`~$ sudo apt install ./MullvadVPN-2025.6_amd64.deb`

The install ends with this notice:

`N: Download is performed unsandboxed as root as file '/home/username/Downloads/MullvadVPN-2025.6_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`

This also happened with the last update, and the workaround I found was to move the .deb file to /tmp and install it from there. So I purge the incorrectly installed version:

`~$ sudo apt purge mullvad-vpn`

This command, incidentally, ends with this which I don't recall seeing previously:

`dpkg: warning: while removing mullvad-vpn, directory '/usr/local/share' not empty so not removed`

I then move it to the /tmp folder and install from there:

`/tmp$ sudo apt install ./MullvadVPN-2025.6_amd64.deb`

The results end without any notice or error message. However, I get the same Javascript Error popup when running Mullvad VPN from the GUI and also when quitting the app, the error pops up again. It usually requires clicking "OK" multiple times before it will close. I will have to use an older version until this is fixed.

**Comment by presentformyfriends** [comment]
Hello? Some guidance on this would be nice. I am unable to use the VPN for the last two months, so not sure why I'm paying for it.

**Comment by hulthe** [comment]
@presentformyfriends our support team ([support@mullvadvpn.net](mailto:support@mullvadvpn.net)) are usually able to give more prompt support than us, the developers.

That said, I looked briefly at your error and it's definitely different from OPs. Looks like the OS is throwing an I/O error when the GUI is trying to log something to disk. The log files are located at `~/.config/Mullvad VPN/logs/frontend-*.log`. Check that the folder `~/.config/Mullvad VPN/` exists and is writeable. Maybe try deleting it.

**Comment by hulthe** [comment]
@LiberteIV your issue should be fixed in 2025.6. Please let us know it it persists.

**Comment by presentformyfriends** [comment]
@hulthe I have neither of those directories. My logs are in /var/log/ as usual. The issue still persists. I've tried email and twitter, both are ignored. Like pulling teeth to get any real support wtf is this??
