### ISSUE TITLE
Mullvad sets lockdown mode (below killswitch) automatically to on since the last update

### ISSUE THREAD

**Issue by MNarath1** [mullvad/mullvadvpn-app#8213]
### Is it a bug?

- [x] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [x] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

After updating to 2025.6 set my  lockdown mode to on (setting below killswitch) despite it beeing on off before the update this caused my device to suddenly refuse any outgoing connection to the internet without using the vpn.

### Expected Behavior

Updating to a new version shouldn't suddenly switch user settings to a possible new default.

### Steps to Reproduce

1. ... Have  lockdown mode set to off on 2025.5
2. ...Update to 2025.6

### Failure Logs

```shell

```

### Operating system version

Fedora KDE 42

### Mullvad VPN app version

2025.6

### Additional Information

With  lockdown mode i am talking about the firewall behavior switch where even when the app is shudown or not connected it will still block a connection to the local network or the internet.

**Comment by MNarath1** [comment]
Dunno how this bug happened maybe since i never toggled that setting it never actually saved a default preference and took the new default behavior for that option?

**Comment by dlon** [comment]
Thanks, this is likely a bug. Do you happen to have logs left (`/var/log/mullvad-vpn/daemon.log`)? They might contain some hint about why reading the settings failed.

**Comment by MNarath1** [comment]
`  GNU nano 8.3                                                                                     /var/log/mullvad-vpn/daemon.log                                                                                                
[2025-05-19 17:58:08.724][mullvad_daemon::version][INFO] Starting mullvad-daemon - 2025.6 2025-05-13
[2025-05-19 17:58:08.724][mullvad_daemon][INFO] Logging to /var/log/mullvad-vpn
[2025-05-19 17:58:08.724][mullvad_daemon::management_interface][INFO] Management interface listening on /var/run/mullvad-vpn
[2025-05-19 17:58:08.724][mullvad_api::address_cache][DEBUG] Loading API addresses from /var/cache/mullvad-vpn/api-ip-address.txt
[2025-05-19 17:58:08.724][mullvad_api::address_cache][DEBUG] Using API address: 
[2025-05-19 17:58:08.725][mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
[2025-05-19 17:58:08.725][mullvad_relay_selector::relay_selector::parsed_relays][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
[2025-05-19 17:58:08.730][mullvad_relay_selector::relay_selector::parsed_relays][DEBUG] Reading relays from /opt/Mullvad VPN/resources/relays.json
[2025-05-19 17:58:08.735][mullvad_relay_selector::relay_selector][INFO] Initialized with 725 cached relays from 2025-05-19 17:42:06.053
[2025-05-19 17:58:08.735][mullvad_api::availability][DEBUG] Pausing background API requests
[2025-05-19 17:58:08.735][mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
[2025-05-19 17:58:08.735][mullvad_daemon::target_state][DEBUG] No cached target state to load
[2025-05-19 17:58:08.736][talpid_core::firewall][INFO] Applying firewall policy: Blocked. Blocking LAN. Allowing endpoint: 
[2025-05-19 17:58:08.809][mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
[2025-05-19 17:58:08.809][mullvad_daemon::api][INFO] Initial offline state - online
[2025-05-19 17:58:08.810][mullvad_api::availability][DEBUG] Resuming API requests due to coming online
[2025-05-19 17:58:08.833][mullvad_api::access][DEBUG] Fetching access token for an account
[2025-05-19 17:58:08.833][mullvad_daemon::geoip][DEBUG] Fetching GeoIpLocation
[2025-05-19 17:58:08.837][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Legacy hyper error
Caused by: client error (Connect)
Caused by: failed to lookup address information: Temporary failure in name resolution
[2025-05-19 17:58:09.238][mullvad_daemon::management_interface][DEBUG] is_performing_post_upgrade
[2025-05-19 17:58:09.240][mullvad_daemon::management_interface][DEBUG] get_account_history
[2025-05-19 17:58:09.241][mullvad_daemon::management_interface][DEBUG] get_tunnel_state
[2025-05-19 17:58:09.243][mullvad_daemon::management_interface][DEBUG] get_device
[2025-05-19 17:58:09.245][mullvad_daemon::management_interface][DEBUG] get_settings
[2025-05-19 17:58:09.245][mullvad_daemon::management_interface][DEBUG] update_device
[2025-05-19 17:58:09.245][mullvad_daemon::management_interface][DEBUG] get_account_data
[2025-05-19 17:58:09.245][mullvad_daemon::management_interface][DEBUG] get_account_history
[2025-05-19 17:58:09.249][mullvad_daemon::management_interface][DEBUG] get_current_api_access_method
[2025-05-19 17:58:09.250][mullvad_daemon::management_interface][DEBUG] get_relay_locations
[2025-05-19 17:58:09.253][mullvad_api::rest][ERROR] Error: HTTP request failed
`
nothing really except that it applies the firewall policy blocked (which was not set to on before 2025.6) or is that just me turning on the vpn tunnel also me saying that its default on now is honestly just a guess i don't know for sure that lockdown mode is now default on on.

**Comment by MNarath1** [comment]
no i do think all of this is before i turned on the vpn

**Comment by mohsunb** [comment]
Hi.

I have been using Mullvad VPN on Fedora Linux for a few months now, with only the default settings. Updating to version 2025.6 seems to have automatically enabled the "Lockdown mode". Judging by the feedback in a Fedora Discussions post about this, it seems like this happened to a lot of people.

**Comment by MNarath1** [comment]
I think now it completly erased my personalized settings since i noticed local network share was also disabled after this update (was on before) as well as my prefered vpn location got also switched to the i think default one you start out with

**Comment by dlon** [comment]
Is it possible that the app was downgraded before you could update to 2025.6? We do not generally support downgrades, and it will result in the settings being wiped (along with lockdown mode being enabled) if they're not compatible.

**Comment by mohsunb** [comment]
I did not manually downgrade the package and since the package comes directly from Mullvad's own RPM repository, I don't think Fedora (or dnf) would play a role here.

**Comment by NotNite** [comment]
Hi, also having this issue on Fedora 42. I updated my system packages and lost internet on the next reboot (using `mullvad-vpn` from the official repository `https://repository.mullvad.net/rpm/stable/mullvad.repo`). I noticed this in the logs of `mullvad-early-boot-blocking.service`, which seems like the issue:

```
May 21 11:43:52 thegame systemd[1]: Starting mullvad-early-boot-blocking.service - Mullvad early boot network blocker...
May 21 11:43:52 thegame mullvad-daemon[23841]: [2025-05-21 11:43:52.483][mullvad_daemon::version][INFO] Starting mullvad-daemon - 2025.6 2025-05-13
May 21 11:43:52 thegame mullvad-daemon[23841]: [2025-05-21 11:43:52.484][mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
May 21 11:43:52 thegame mullvad-daemon[23841]: [2025-05-21 11:43:52.485][mullvad_daemon::settings][WARN] Error: Failed to load settings. Using defaults.
May 21 11:43:52 thegame mullvad-daemon[23841]: Caused by: Unable to parse settings file
May 21 11:43:52 thegame mullvad-daemon[23841]: Caused by: unknown variant `any`, expected `openvpn` or `wireguard` at line 13 column 30
May 21 11:43:52 thegame mullvad-daemon[23841]: [2025-05-21 11:43:52.487][mullvad_daemon::early_boot_firewall][INFO] Applying firewall policy Blocked. Blocking LAN. Allowing endpoint: none
May 21 11:43:52 thegame mullvad-daemon[23841]: [2025-05-21 11:43:52.487][talpid_core::firewall][INFO] Applying firewall policy: Blocked. Blocking LAN. Allowing endpoint: none
May 21 11:43:52 thegame systemd[1]: mullvad-early-boot-blocking.service: Deactivated successfully.
May 21 11:43:52 thegame systemd[1]: Finished mullvad-early-boot-blocking.service - Mullvad early boot network blocker.
```

Unfortunately I don't have a copy of the config before this boot so I can't say what it looked like. This error only appeared once on the boot after I updated, then I presume the default settings file was written, which re-enabled lockdown mode. I did not downgrade (my previous version was 2025.5).

**Comment by NotNite** [comment]
Looks like it might have been https://github.com/mullvad/mullvadvpn-app/commit/be0877a65e0f5e53a06ca7ee7a1303b5716b41dd given how it was "any", and line 13 in my newly-generated config file is `tunnel_protocol`.

**Comment by dlon** [comment]
Thank you, @NotNite. We'll fix this ASAP.

**Comment by emanuc** [comment]
I can confirm the issue, it happened to me as well during the last upgrade; I'm on Fedora 42. It took me a while to realize that Mullvad was the cause.

```
Pacchetti installati
Name            : mullvad-vpn
Epoch           : 0
Version         : 2025.6
Release         : 1
Architecture    : x86_64
Installed size  : 334.9 MiB
Source          : mullvad-vpn-2025.6-1.src.rpm
From repository : mullvad-stable
Summary         : Mullvad VPN client
URL             : https://github.com/mullvad/mullvadvpn-app#readme
License         : GPL-3.0
Description     : Mullvad VPN client
Vendor          : Mullvad VPN <support@mullvadvpn.net>
```

**Comment by kepford** [comment]
Fedora 41 user here. Had the same issue after running `dnf update`.  Figured it out by reviewing logs. Solved by uninstalling the app. Will test once a new release is out.

**Comment by pat-githubber** [comment]
Bug still persists: I just updated to version 2025.5 MacOS 15.5 Apple M1. I was very confused.

**Comment by NotNite** [comment]
> Bug still persists: I just updated to version 2025.5 MacOS 15.5 Apple M1. I was very confused.

The fix is [still in the beta channels](https://github.com/mullvad/mullvadvpn-app/releases/tag/2025.7-beta1) and hasn't been properly released yet. I imagine it will arrive in 2025.7.
