### ISSUE TITLE
Split tunneling stopped working on Mac OS 26 beta 2

### ISSUE THREAD

**Issue by EinTim23** [mullvad/mullvadvpn-app#8375]
### Is it a bug?

- [x] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [x] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

After connection no app seems to have internet connection anymore except mullvad itself. ICMP pings to 1.1.1.1 timeout. The settings and/or reinstalling the app don't seem to influence this.

### Expected Behavior

Let me connect to the internet

### Steps to Reproduce

1. Install latest mac os 26 beta
2. Install mullvad
3. Profit(Or don't profit)

### Failure Logs

```shell

```

### Operating system version

Mac os 26 beta2

### Mullvad VPN app version

2025.5

**Comment by MarkusPettersson98** [comment]
Hello @EinTim23, thanks for your report! Would you mind trying out the latest `2025.7` app which we released today and see if the issue persists? 💛

**Comment by EinTim23** [comment]
The underlying issue still seems to exist, but the behaviour i'm getting now is a bit different. Internet started working again but icmp pings are still timing out

**Comment by MarkusPettersson98** [comment]
Alright, we'll look into it. Thanks!

**Comment by cameronaaron** [comment]
On Mac OS 26 beta 2 and not having an issue @EinTim23 are you using an intel or a M chip

**Comment by MarkusPettersson98** [comment]
I just tried macOS 26 beta 2 on an M1 mac, and I could not reproduce your issue @EinTim23 :s 

If the issue persists, would you mind sending us / submitting logs? Scrubbed logs can be exported in the app if you go to `Settings > Support > Report a problem > View logs`. If you send the logs to our support team, please reference this issue and/or me  :blush:

**Comment by EinTim23** [comment]
@cameronaaron I'm on an apple silicon mac. @MarkusPettersson98 I just sent in the logs from the app, I hope that there is something interesting in there

**Comment by EinTim23** [comment]
Okay, the Mullvad support came back to me and told me to disable split tunneling, after which it started working again. I always had it enabled without any apps set to split tunnel, and for some reason after updating from beta1 to beta2 it decided to break, so I guess this isn't really a bug inside the app?

EDIT: trying to add apps to the split tunnel now doesn't appear to do anything tho, the plus button just shows no reaction, the app still seems to be split tunneled tho

**Comment by MarkusPettersson98** [comment]
Great that the app started working again, and a huge thanks for providing logs! We found a strange error message in the split tunneling code which we will look into - there might actually be a regression in `eslogger` in macOS 26...

I'll go ahead and change the title of this issue to be a bit more specific. If you object to this, please let me know.

Once again, thanks 💛

**Comment by lewislarsen** [comment]
This issue also affects MacOS 26 Beta 3. I updated a couple of days ago and I was unable to establish a connection with Mullvad (with Split Tunnelling enabled) afterwards. Disabling Split Tunnel fixes it and allows a connection to be made.

I am using 2025.7 but 2025.6 also shared this problem.

**Update**

I received a response from Mullvad Support, and these settings resolved my problems. They might work for you as well.

> You can also try to go to the Mullvad app settings > VPN settings > WireGuard settings and set these settings:
> 
> * MTU: 1280
> * Obfuscation: UDP-over-TCP

(Credits to Stefan from Mullvad for telling me about it!)

**Comment by stylobasket** [comment]
Hi,

I’m still experiencing the original issue.

I applied the recommended settings: 

> MTU set to 1280 and obfuscation set to UDP-over-TCP

. As soon as I enable split-tunneling and connect to the VPN, I completely lose Internet access. The VPN shows as connected, but no traffic gets through. Nothing loads in browsers or apps.

I’ve tested this with different apps selected in the split-tunneling settings. I also tried uninstalling and reinstalling Mullvad, and made sure no other VPN or network tool is interfering. Same result every time.

I’m connecting from France, in case that detail helps.

Let me know if you need any logs or additional info. Happy to assist.

Thanks for your time and support.

**Comment by stylobasket** [comment]
**[Resolved] macOS (v2025.7) – Split-tunneling only works with MTU 1280 + UDP-over-TCP, heavy speed loss**

**Environment**

	•	macOS 14.x
	•	Mullvad VPN 2025.7 (latest available on website)
	•	No “Beta” toggle in Mullvad VPN Loader

**What I did :** 

	1.	Set MTU to 1280 and enabled Obfuscation: UDP-over-TCP.
	2.	Removed Mullvad from System Settings ▸ Privacy & Security ▸ Full Disk Access, added it back, then relaunched.
	3.	Re-configured split tunneling: removed Firefox from exclusions, added it again, toggled split tunneling off/on,  restarted Firefox.

**Result :**

	•	Split tunneling now works: Firefox shows my real IP on https://mullvad.net/check while other traffic stays on the VPN.
	•	Connection stability is good, but MTU 1280 + UDP-over-TCP reduces throughput noticeably.

**Question / Issue :** 

Do we need to keep these restrictive settings until a future release, or is a less speed-hungry fix planned? Any guidance on mitigating the performance hit would be appreciated.

Thanks for your help!

**Comment by cameronaaron** [comment]
@EinTim23 This should be resolved in Beta 4 can you confirm

**Comment by lewislarsen** [comment]
> [@EinTim23](https://github.com/EinTim23) This should be resolved in Beta 4 can you confirm

I can't speak for @EinTim23 , however I'm on Beta 4 and split tunneling is still broken on 2025.8-beta1 at least.

**Comment by MarkusPettersson98** [comment]
We are aware of some issues in our split tunneling implementation that will break in the coming macOS release. We are working on a fix https://github.com/mullvad/mullvadvpn-app/pull/8565 :blush:

Thanks everyone for your responses, they make our lives easier 💛

**Comment by stylobasket** [comment]
> We are aware of some issues in our split tunneling implementation that will break in the coming macOS release. We are working on a fix [#8565](https://github.com/mullvad/mullvadvpn-app/pull/8565) 😊
> 
> Thanks everyone for your responses, they make our lives easier 💛

Thank you for this work, I think we're all looking forward to having this feature up and running again!

**Comment by EinTim23** [comment]
The latest beta build fixes this. Thanks for your work!

**Comment by stylobasket** [comment]
I would like to thank the Mullvad team for resolving this issue!

**Comment by gitternand** [comment]
This is still not working on 2025.13 and Tahoe 26.1 (M4 Mac), right?
I have the exact same issue ...

by the way, 2025.14-beta1 doesn't seem to fix it either.

**Comment by MarkusPettersson98** [comment]
> This is still not working on 2025.13 and Tahoe 26.1 (M4 Mac), right? I have the exact same issue ...
> 
> by the way, 2025.14-beta1 doesn't seem to fix it either.

Split tunneling should work fine on Tahoe. At least from our testing. [Have you given full disk access to our app](https://mullvad.net/en/help/split-tunneling-with-the-mullvad-app#macosapp)? If you keep running into issues, please either contact our support (support@mullvadvpn.net) or document how to reproduce the issue, gather logs and then open a new issue here on GitHub. Thanks!

**Comment by gitternand** [comment]
Thanks @MarkusPettersson98 !
I still have that weird bug, were giving full disk access won't stick.
I know there was an issue somewhere but I can't seem to find it anymore, sorry :/

**Comment by MarkusPettersson98** [comment]
> Thanks [@MarkusPettersson98](https://github.com/MarkusPettersson98) ! I still have that weird bug, were giving full disk access won't stick. I know there was an issue somewhere but I can't seem to find it anymore, sorry :/

I know which one you're talking about, and it's super annoying. Unfortunately it's a macOS bug, so we can't do much about that bug in particular:(

**Comment by gitternand** [comment]
> I know which one you're talking about, and it's super annoying. Unfortunately it's a macOS bug, so we can't do much about that bug in particular:(

Thanks! As far as I know the bug in 26.1 is with giving full disk access to files that are not apps (so, other binaries, for example). (and I've tried the workaround you can find for this online, it doesn't work with Mullvad)
I've been turning on and off full disk access for (literally) all my apps in the last 20 minutes and the only option that won't stick is Mullvad. So is this really a macOS-only bug or is it a Mullvad<->macOS bug?

Anyway, I'll contact the Support as well. But the last time I've contacted them about this issue they've ghosted me :/

Edit: I also just tried re-installing the app which also didn't change anything :(
